// Consultas migradas del PHP adjunto; solo los filtros enumerados generan fragmentos SQL.
export type Rubro = typeof RUBROS[number];
export const RUBROS = ['Neural','Kapsch Americas','Kapsch Zona 16','Kapsch Serie K','Velocidad','Vía Exclusiva','Serie B','Neonet POS','Fotomultas','Cepos'] as const;
export const CAMARAS: Record<string,string> = {
  'TODAS': 'Todas las cámaras',
  '12555': 'Estacion Tivoli 6a avenida, 4-02 zona 9',
  '12556': '7ma. avenida y 13 calle zona 9',
  '5635': 'Estacion Terminal, 6 Avenida y 2 calle zona 9',
  '12497': 'Avenida Bolivar y 32 calle zona 8',
  '12501': 'Mariscal Norte 15 calle y Aguillar Batres zona 12',
  '12502': 'Mariscal Sur 13 calle y Aguillar Batres zona 12',
  '5348': 'Estacion IGSS 10 Calle y 7 avenida zona 9',
  '12498': 'Avenida Bolivar y 31 calle zona 3',
  '5351': '6ta.calle y 6ta.avenida zona 9',
  '12716': '6ta.calle y 6ta.avenida zona 9',
  '12493': '6 avenida 22 calle zona 1',
  '12705': 'Estacion terminal 6av 2a calle z9',
  '12714': 'ESTACION IGSS 7 AVENIDA ZONA 9',
  '12748': 'Cámara de 6 avenida entre 22 y 24 calle zona 4 pista derecha',
  '12747': '7 avenida 1 calle zona 9',
  '12745': 'Cámara de 29 calle Aguilar Batres al Sur zona 11',
};
export function filter(a: string,b: string,kind: Rubro): string {
 switch(kind) {
  case 'Neural': return ` AND ${a}.SERIE='M' AND ${a}.LUGAR IN ('Petapa 31 calle z12','Proceres diagonal 6 z10','Blvd_Los_Proceres_18av_zona_10','Ave_Petapa_31c_zona_12','NLO LPR PETAPE Y CLL 31')`;
  case 'Kapsch Americas': return ` AND ${a}.SERIE='M' AND ${a}.LUGAR='Avenida_Las_Americas_16_Calle_zona_13'`;
  case 'Kapsch Zona 16': return ` AND ${a}.SERIE='M' AND ${a}.LUGAR='Boulevard_Landivar_4_Avenida_Colonia_Camposeco_zona_16'`;
  case 'Kapsch Serie K': return ` AND ${a}.SERIE='K'`;
  case 'Velocidad': return ` AND ${a}.SERIE='L' AND ${b}.REGLA=65`;
  case 'Vía Exclusiva': return ` AND ${a}.SERIE='L' AND ${b}.REGLA=79`;
  case 'Serie B': return ` AND ${a}.SERIE='B'`;
  case 'Neonet POS': return ` AND ${a}.SERIE='N'`;
  case 'Fotomultas': return ` AND ${a}.SERIE='L' AND ${b}.REGLA NOT IN (79,65) AND ${a}.OBSERVACIONES='C.LPR SEMAFORIZACION'`;
  default: throw new Error('Rubro no reconocido');
 }
}
export const sqlRubro = (kind: Rubro) => `SELECT
      (SELECT COUNT(DISTINCT A.SERIE||'-'||A.REMISION) FROM EMT_REMISIONES A JOIN EMT_DETALLES_INFRACCION B ON B.SERIE=A.SERIE AND B.REMISION=A.REMISION WHERE A.FECHA>=TO_DATE(:inicio,'DD-MM-YYYY') AND A.FECHA<TO_DATE(:fin,'DD-MM-YYYY')+1 ${filter('A','B',kind)}) TOTAL,
      (SELECT NVL(SUM(B.MONTO),0) FROM EMT_REMISIONES A JOIN EMT_DETALLES_INFRACCION B ON B.SERIE=A.SERIE AND B.REMISION=A.REMISION WHERE A.FECHA>=TO_DATE(:inicio,'DD-MM-YYYY') AND A.FECHA<TO_DATE(:fin,'DD-MM-YYYY')+1 ${filter('A','B',kind)}) MONTO,
      (SELECT COUNT(DISTINCT C.SERIE||'-'||C.REMISION) FROM TB_DOCUMENTOS_EMT X JOIN TB_DETALLE_DOCUMENTOS_EMT Y ON X.TIPO_FACTURA=Y.TIPO_FACTURA AND X.SERIE=Y.SERIE AND X.DOCUMENTO=Y.DOCUMENTO JOIN EMT_REMISIONES C ON C.SERIE=Y.SERIE_REMISION AND C.REMISION=Y.NUMERO_REMISION JOIN EMT_DETALLES_INFRACCION D ON D.SERIE=C.SERIE AND D.REMISION=C.REMISION WHERE X.FECHA>=TO_DATE(:inicio,'DD-MM-YYYY') AND X.FECHA<TO_DATE(:fin,'DD-MM-YYYY')+1 AND X.ESTATUS='P' AND C.STATUS='N' AND C.ESTATUS_TIPPAGO IS NOT NULL AND (Y.TIPO_COBRO,Y.COBRO,Y.CUENTA_COBRO) IN ((2,21,1),(2,24,1),(2,6,1),(2,20,1),(17,2,1),(17,1,1),(17,15,1),(17,20,2)) ${filter('C','D',kind)}) TOTAL_PAGADO,
      (SELECT NVL(SUM(Y.VALOR),0) FROM TB_DOCUMENTOS_EMT X JOIN TB_DETALLE_DOCUMENTOS_EMT Y ON X.TIPO_FACTURA=Y.TIPO_FACTURA AND X.SERIE=Y.SERIE AND X.DOCUMENTO=Y.DOCUMENTO JOIN EMT_REMISIONES C ON C.SERIE=Y.SERIE_REMISION AND C.REMISION=Y.NUMERO_REMISION JOIN EMT_DETALLES_INFRACCION D ON D.SERIE=C.SERIE AND D.REMISION=C.REMISION WHERE X.FECHA>=TO_DATE(:inicio,'DD-MM-YYYY') AND X.FECHA<TO_DATE(:fin,'DD-MM-YYYY')+1 AND X.ESTATUS='P' AND C.STATUS='N' AND C.ESTATUS_TIPPAGO IS NOT NULL AND (Y.TIPO_COBRO,Y.COBRO,Y.CUENTA_COBRO) IN ((2,21,1),(2,24,1),(2,6,1),(2,20,1),(17,2,1),(17,1,1),(17,15,1),(17,20,2)) ${filter('C','D',kind)}) MONTO_PAGADO FROM DUAL`;
export const sqlDetalle = (kind: Rubro) => `WITH I AS (SELECT TRUNC(A.FECHA) DIA,COUNT(DISTINCT A.SERIE||'-'||A.REMISION) TOTAL,NVL(SUM(B.MONTO),0) MONTO FROM EMT_REMISIONES A JOIN EMT_DETALLES_INFRACCION B ON B.SERIE=A.SERIE AND B.REMISION=A.REMISION WHERE A.FECHA>=TO_DATE(:inicio,'DD-MM-YYYY') AND A.FECHA<TO_DATE(:fin,'DD-MM-YYYY')+1 ${filter('A','B',kind)} GROUP BY TRUNC(A.FECHA)),
    P AS (SELECT TRUNC(X.FECHA) DIA,COUNT(DISTINCT C.SERIE||'-'||C.REMISION) TOTAL_PAGADO,NVL(SUM(Y.VALOR),0) MONTO_PAGADO FROM TB_DOCUMENTOS_EMT X JOIN TB_DETALLE_DOCUMENTOS_EMT Y ON X.TIPO_FACTURA=Y.TIPO_FACTURA AND X.SERIE=Y.SERIE AND X.DOCUMENTO=Y.DOCUMENTO JOIN EMT_REMISIONES C ON C.SERIE=Y.SERIE_REMISION AND C.REMISION=Y.NUMERO_REMISION JOIN EMT_DETALLES_INFRACCION D ON D.SERIE=C.SERIE AND D.REMISION=C.REMISION WHERE X.FECHA>=TO_DATE(:inicio,'DD-MM-YYYY') AND X.FECHA<TO_DATE(:fin,'DD-MM-YYYY')+1 AND X.ESTATUS='P' AND C.STATUS='N' AND C.ESTATUS_TIPPAGO IS NOT NULL AND (Y.TIPO_COBRO,Y.COBRO,Y.CUENTA_COBRO) IN ((2,21,1),(2,24,1),(2,6,1),(2,20,1),(17,2,1),(17,1,1),(17,15,1),(17,20,2)) ${filter('C','D',kind)} GROUP BY TRUNC(X.FECHA))
    SELECT TO_CHAR(NVL(I.DIA,P.DIA),'DD-MM-YYYY') DIA,NVL(I.TOTAL,0) TOTAL,NVL(I.MONTO,0) MONTO,NVL(P.TOTAL_PAGADO,0) TOTAL_PAGADO,NVL(P.MONTO_PAGADO,0) MONTO_PAGADO FROM I FULL OUTER JOIN P ON P.DIA=I.DIA ORDER BY NVL(I.DIA,P.DIA)`;
export const sqlCepos = `SELECT COUNT(*) TOTAL,COUNT(*)*500 MONTO,SUM(CASE WHEN C.ESTATUS='P' THEN 1 ELSE 0 END) TOTAL_PAGADO,SUM(CASE WHEN C.ESTATUS='P' THEN 500 ELSE 0 END) MONTO_PAGADO FROM TB_CEPOS_PMT C WHERE C.FECHA>=TO_DATE(:inicio,'DD-MM-YYYY') AND C.FECHA<TO_DATE(:fin,'DD-MM-YYYY')+1`;
export const sqlDetalleCepos = `SELECT TO_CHAR(TRUNC(C.FECHA),'DD-MM-YYYY') DIA,COUNT(*) TOTAL,COUNT(*)*500 MONTO,SUM(CASE WHEN C.ESTATUS='P' THEN 1 ELSE 0 END) TOTAL_PAGADO,SUM(CASE WHEN C.ESTATUS='P' THEN 500 ELSE 0 END) MONTO_PAGADO FROM TB_CEPOS_PMT C WHERE C.FECHA>=TO_DATE(:inicio,'DD-MM-YYYY') AND C.FECHA<TO_DATE(:fin,'DD-MM-YYYY')+1 GROUP BY TRUNC(C.FECHA) ORDER BY TRUNC(C.FECHA)`;
export const sqlCamara = (cameraFilter: string) => `WITH C AS (SELECT TRUNC(A.FECHA) DIA,A.MOTIVO_RECHAZO,V.TIPO_VEHICULO,V.VEHICULO,COUNT(*) N FROM TB_REGISTRO_CAMARA A JOIN EMT_VEHICULOS V ON V.VEHI_TIPO_PLACA=SUBSTR(A.PLACA,1,1) AND V.PLACA=SUBSTR(A.PLACA,2) WHERE A.FECHA>=TO_DATE(:inicio,'DD-MM-YYYY') AND A.FECHA<TO_DATE(:fin,'DD-MM-YYYY')+1 ${cameraFilter} GROUP BY TRUNC(A.FECHA),A.MOTIVO_RECHAZO,V.TIPO_VEHICULO,V.VEHICULO), R AS (SELECT DISTINCT TRUNC(FECHA) DIA,TIPO_VEHICULO,VEHICULO FROM EMT_REMISIONES WHERE FECHA>=TO_DATE(:inicio,'DD-MM-YYYY') AND FECHA<TO_DATE(:fin,'DD-MM-YYYY')+1) SELECT TO_CHAR(C.DIA,'DD-MM-YYYY') DIA,SUM(C.N) CAPTADAS,SUM(CASE WHEN R.VEHICULO IS NOT NULL THEN C.N ELSE 0 END) IMPUESTAS,SUM(CASE WHEN R.VEHICULO IS NULL THEN C.N ELSE 0 END) NO_IMPUESTAS,SUM(CASE WHEN C.MOTIVO_RECHAZO=8 THEN C.N ELSE 0 END) PENDIENTES,SUM(CASE WHEN C.MOTIVO_RECHAZO IS NULL THEN C.N ELSE 0 END) BUSES FROM C LEFT JOIN R ON R.DIA=C.DIA AND R.TIPO_VEHICULO=C.TIPO_VEHICULO AND R.VEHICULO=C.VEHICULO GROUP BY C.DIA ORDER BY C.DIA`;
